version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: apple
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  worker:
    build:
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:apple@postgres:5432/postgres
    depends_on:
      - redis
      - postgres

volumes:
  postgres-data: